POST http://localhost:8080/api/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM2NzcyNDU3LCJleHAiOjE3MzkzNjQ0NTd9.bujzZZrrK5DaJd9jl5G4A7qNAet8gQLmd4UL-2aJffA
//Student  1=> Your name

# {
    # "data": {
    # "name": "Chiraphat Phengphit",
    # "mobile": "0660808283",
    # "cardId": "1929900799399"
    # }
# }
//Student 2 => Your Friend
{
    "data": {
    "name": "Penpitcha Prayonghom",
    "mobile": "0985267029",
    "cardId": "1169800238597"
    }
}